In [1]:
### pandas is used for data manipulation library in python, widely used for data analysis and data cleaning two primary ds series and DataFrame. Series is 1d array like object data frame is 2d mutable and potentially heterogeneous tabular ds with labelled axes(rows and columns)
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-macosx_11_0_arm64.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 980.1 kB/s  0:00:10m0:00:010:01
Installing collected packages: pandas
Successfully installed pandas-3.0.6

In [41]:
import pandas as pd
## Series
## 1d series array like object can hold any data type
series=pd.Series([1,2,3,4,5])
print(series)
print(type(series))

series.describe()

## create a series from dictionary
van={
    'name':'Vansh Vats',
    'class':'CSE_AI',
    'roll':18
}

print(type(van))

series=pd.Series(van)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
<class 'dict'>
<class 'pandas.Series'>

In [10]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## DataFrame create a DataFrame from a dictionary of list
data={
    'name':['Vansh','Daksh','Keshav'],
    'age':[18,16,17],
    'City':['Katewara','Katewara','Katewara']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

     name  age      City
0   Vansh   18  Katewara
1   Daksh   16  Katewara
2  Keshav   17  Katewara
<class 'pandas.DataFrame'>

In [15]:
import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [34]:
import pandas as pd
data=[
    {'name':'Vansh','age':18,'place':'Delhi'},
    {'name':'Daksh','age':16,'place':'Bawana'},
    {'name':'Keshav','age':17,'place':'Katewara'},
    {'name':'Ayush','age':19,'place':'Bihar'},
    {'name':'Anurag','age':18,'place':'Alipur'}
]
df=pd.DataFrame(data)
print(df)
df['name']

import numpy as np

arr=np.array([10,20,30,40,50])
print(np.mean(arr))

     name  age     place
0   Vansh   18     Delhi
1   Daksh   16    Bawana
2  Keshav   17  Katewara
3   Ayush   19     Bihar
4  Anurag   18    Alipur
30.0

In [38]:
df['Salary']=[10000,20000,30000,40000,50000]
print(df)
df.drop('Salary',axis=1,inplace=True)

     name  age     place  Salary
0   Vansh   18     Delhi   10000
1   Daksh   16    Bawana   20000
2  Keshav   17  Katewara   30000
3   Ayush   19     Bihar   40000
4  Anurag   18    Alipur   50000

In [37]:
df

     name  age     place  Salary
0   Vansh   18     Delhi   10000
1   Daksh   16    Bawana   20000
2  Keshav   17  Katewara   30000
3   Ayush   19     Bihar   40000
4  Anurag   18    Alipur   50000

In [39]:
df['age']=df['age']+1
df

     name  age     place
0   Vansh   19     Delhi
1   Daksh   17    Bawana
2  Keshav   18  Katewara
3   Ayush   20     Bihar
4  Anurag   19    Alipur

In [ ]:
df=pd.read_csv()
df.head()

In [ ]:
df=pd.read_csv()
df.head(5)
df.describe()

             age
count   5.000000
mean   18.600000
std     1.140175
min    17.000000
25%    18.000000
50%    19.000000
75%    19.000000
max    20.000000

In [8]:
import pandas as pd
data=[1,2,3,4,5]
print(type(data))
data=pd.Series(data)
print(type(data))

van=[
    {'name':'Vansh','age':18,'course':'B.Tech','college':'Mait'},
    {'name':'Keshav','age':18,'course':'B.Tech','college':'Bvcoe'},
    {'name':'Daksh','age':18,'course':'B.Tech','college':'Bvcoe'},
    {'name':'Anurag','age':18,'course':'B.Tech','college':'Mait'}
]

df=pd.DataFrame(van)
print(df)

df['name']
df['Salary']:[10000,20000,10000,30000]
print(df)

<class 'list'>
<class 'pandas.Series'>
     name  age  course college
0   Vansh   18  B.Tech    Mait
1  Keshav   18  B.Tech   Bvcoe
2   Daksh   18  B.Tech   Bvcoe
3  Anurag   18  B.Tech    Mait
     name  age  course college
0   Vansh   18  B.Tech    Mait
1  Keshav   18  B.Tech   Bvcoe
2   Daksh   18  B.Tech   Bvcoe
3  Anurag   18  B.Tech    Mait